server:
  port: 8761
spring:
  application:
    name: eureka-server

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: ${REGISTER_WITH_EUREKA:false}
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}